services:
  mysql-users-db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-network
        
  pruebatecnica:
    image: pruebatecnica
    build:
      context: .
      dockerfile: PruebaTecnica/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__ConnectionDb=Server=mysql-users-db;Port=3306;Database=userdb;User=user;Password=1234;
    depends_on:
      - mysql-users-db
    networks:
      - user-network
    
volumes:
  mysql_data:
      
networks:
  user-network:
  

